package ingressgen

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func validManifest() Manifest {
	return Manifest{
		SchemaVersion: 1,
		Chain:         "DOCKER-USER",
		Rules: []Rule{
			{Comment: "Keep replies", Args: []string{"-m", "conntrack", "--ctstate", "ESTABLISHED,RELATED", "-j", "RETURN"}},
			{Comment: "Fail closed", Args: []string{"-j", "DROP"}},
		},
	}
}

func TestRenderDeterministicDefaultDenyRuleset(t *testing.T) {
	rendered, err := Render(validManifest())
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by ingressgen. Edit the manifest, never this file.\n" +
		"*filter\n:DOCKER-USER - [0:0]\n-F DOCKER-USER\n" +
		"# Keep replies\n-A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN\n" +
		"# Fail closed\n-A DOCKER-USER -j DROP\nCOMMIT\n"
	if string(rendered) != want {
		t.Fatalf("rendered rules mismatch\nwant:\n%s\ngot:\n%s", want, rendered)
	}
}

func TestValidateRejectsUnsafeOrFailOpenManifests(t *testing.T) {
	cases := []struct {
		name string
		edit func(*Manifest)
		want string
	}{
		{"unsupported version", func(m *Manifest) { m.SchemaVersion = 2 }, "schema_version"},
		{"unsafe chain mutation", func(m *Manifest) { m.Rules[0].Args = []string{"-F", "INPUT", "-j", "RETURN"} }, "manage chains"},
		{"long chain mutation", func(m *Manifest) { m.Rules[0].Args = []string{"--new-chain", "X", "-j", "RETURN"} }, "manage chains"},
		{"newline injection", func(m *Manifest) { m.Rules[0].Args[0] = "-m\n-A INPUT -j ACCEPT" }, "unsafe argument"},
		{"space injection", func(m *Manifest) { m.Rules[0].Args[0] = "-m conntrack" }, "unsafe argument"},
		{"wrong chain", func(m *Manifest) { m.Chain = "INPUT" }, "DOCKER-USER"},
		{"unconditional return", func(m *Manifest) { m.Rules[0].Args = []string{"-j", "RETURN"} }, "fail-open"},
		{"missing terminal drop", func(m *Manifest) { m.Rules[len(m.Rules)-1].Args = []string{"-j", "RETURN"} }, "final rule"},
		{"duplicate rule", func(m *Manifest) { m.Rules = append([]Rule{m.Rules[0]}, m.Rules...) }, "duplicates"},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			manifest := validManifest()
			test.edit(&manifest)
			if err := manifest.Validate(); err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("Validate() error = %v, want substring %q", err, test.want)
			}
		})
	}
}

func TestApplyAlwaysTestsAndUsesNoFlush(t *testing.T) {
	dir := t.TempDir()
	logPath := filepath.Join(dir, "calls")
	fake := filepath.Join(dir, "iptables-restore")
	script := "#!/bin/sh\nprintf '%s\\n' \"$*\" >> \"$CALL_LOG\"\ncat >/dev/null\n"
	if err := os.WriteFile(fake, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("CALL_LOG", logPath)
	if err := Apply(context.Background(), fake, []byte("rules\n")); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(logPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "--test --noflush\n--noflush\n" {
		t.Fatalf("application argv = %q", got)
	}
}

func TestCheckDetectsDrift(t *testing.T) {
	if err := Check([]byte("same\n"), []byte("same\n")); err != nil {
		t.Fatal(err)
	}
	if err := Check([]byte("new\n"), []byte("old\n")); err == nil {
		t.Fatal("Check() accepted drift")
	}
}
