// Package ingressgen renders a complete, default-deny DOCKER-USER ruleset
// from a small YAML manifest. Projects own policy; this package owns the safe,
// deterministic iptables-restore shape and drift comparison.
package ingressgen

import (
	"bytes"
	"fmt"
	"os"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "# Generated by ingressgen. Edit the manifest, never this file.\n"

var chainPattern = regexp.MustCompile(`^[A-Z][A-Z0-9_-]*$`)

type Manifest struct {
	SchemaVersion int    `yaml:"schema_version" json:"schema_version"`
	Chain         string `yaml:"chain" json:"chain"`
	Rules         []Rule `yaml:"rules" json:"rules"`
}

type Rule struct {
	Comment string   `yaml:"comment,omitempty" json:"comment,omitempty"`
	Args    []string `yaml:"args" json:"args"`
}

func Load(path string) (Manifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Manifest{}, err
	}
	var manifest Manifest
	if err := yaml.Unmarshal(raw, &manifest); err != nil {
		return Manifest{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if err := manifest.Validate(); err != nil {
		return Manifest{}, fmt.Errorf("validate %s: %w", path, err)
	}
	return manifest, nil
}

func (m Manifest) Validate() error {
	if m.SchemaVersion != 1 {
		return fmt.Errorf("unsupported schema_version %d", m.SchemaVersion)
	}
	if !chainPattern.MatchString(m.Chain) {
		return fmt.Errorf("invalid chain %q", m.Chain)
	}
	if len(m.Rules) == 0 {
		return fmt.Errorf("rules must not be empty")
	}
	seen := make(map[string]struct{}, len(m.Rules))
	for index, rule := range m.Rules {
		if len(rule.Args) < 2 {
			return fmt.Errorf("rule %d needs arguments and a jump target", index+1)
		}
		hasJump := false
		for argIndex, arg := range rule.Args {
			if arg == "" || strings.ContainsAny(arg, "\r\n\x00") {
				return fmt.Errorf("rule %d has an empty or unsafe argument", index+1)
			}
			if arg == "-A" || arg == "-I" || arg == "-F" || arg == "--append" || arg == "--insert" || arg == "--flush" {
				return fmt.Errorf("rule %d may not manage chains", index+1)
			}
			if (arg == "-j" || arg == "--jump") && argIndex+1 < len(rule.Args) {
				hasJump = true
			}
		}
		if !hasJump {
			return fmt.Errorf("rule %d has no jump target", index+1)
		}
		key := strings.Join(rule.Args, "\x00")
		if _, duplicate := seen[key]; duplicate {
			return fmt.Errorf("rule %d duplicates an earlier rule", index+1)
		}
		seen[key] = struct{}{}
	}
	last := m.Rules[len(m.Rules)-1].Args
	if len(last) != 2 || last[0] != "-j" || last[1] != "DROP" {
		return fmt.Errorf("final rule must be exactly [-j, DROP]")
	}
	return nil
}

func Render(m Manifest) ([]byte, error) {
	if err := m.Validate(); err != nil {
		return nil, err
	}
	var output bytes.Buffer
	output.WriteString(generatedHeader)
	fmt.Fprintf(&output, "*filter\n:%s - [0:0]\n-F %s\n", m.Chain, m.Chain)
	for _, rule := range m.Rules {
		if rule.Comment != "" {
			for _, line := range strings.Split(rule.Comment, "\n") {
				fmt.Fprintf(&output, "# %s\n", line)
			}
		}
		fmt.Fprintf(&output, "-A %s %s\n", m.Chain, strings.Join(rule.Args, " "))
	}
	output.WriteString("COMMIT\n")
	return output.Bytes(), nil
}

func Check(rendered, existing []byte) error {
	if !bytes.Equal(rendered, existing) {
		return fmt.Errorf("generated rules drift: render the manifest and commit the result")
	}
	return nil
}
