package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func runIngressgen(t *testing.T, args ...string) (string, error) {
	t.Helper()
	var out bytes.Buffer
	command, err := (App{Stdout: &out, Stderr: &out}).Command("ingressgen")
	if err != nil {
		t.Fatal(err)
	}
	command.SetArgs(args)
	err = command.Execute()
	return out.String(), err
}

func writeIngressManifest(t *testing.T, chain string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "ingress.yaml")
	content := "schema_version: 1\nchain: " + chain + "\nrules:\n" +
		"  - args: [-m, conntrack, --ctstate, 'ESTABLISHED,RELATED', -j, RETURN]\n" +
		"  - args: [-j, DROP]\n"
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestIngressgenRenderCheckAndJSON(t *testing.T) {
	manifest := writeIngressManifest(t, "DOCKER-USER")
	out, err := runIngressgen(t, "render", manifest)
	if err != nil || !strings.HasPrefix(out, "# Generated by ingressgen") {
		t.Fatalf("human render = %q, %v", out, err)
	}

	rulesPath := filepath.Join(t.TempDir(), "docker-user.rules")
	out, err = runIngressgen(t, "render", manifest, "-o", rulesPath)
	if err != nil || !strings.Contains(out, "wrote "+rulesPath) {
		t.Fatalf("file render = %q, %v", out, err)
	}
	out, err = runIngressgen(t, "check", manifest, rulesPath)
	if err != nil || !strings.Contains(out, "matches") {
		t.Fatalf("check = %q, %v", out, err)
	}

	out, err = runIngressgen(t, "render", manifest, "--json")
	if err != nil {
		t.Fatal(err)
	}
	var rendered struct {
		Status  string `json:"status"`
		Written bool   `json:"written"`
		Rules   string `json:"rules"`
	}
	if err := json.Unmarshal([]byte(out), &rendered); err != nil || rendered.Status != "ok" || rendered.Written || rendered.Rules == "" {
		t.Fatalf("render JSON = %q, %+v, %v", out, rendered, err)
	}

	jsonPath := filepath.Join(t.TempDir(), "json.rules")
	out, err = runIngressgen(t, "render", manifest, "-o", jsonPath, "--json")
	if err != nil {
		t.Fatal(err)
	}
	var fileResult struct {
		Output  string `json:"output"`
		Written bool   `json:"written"`
	}
	if err := json.Unmarshal([]byte(out), &fileResult); err != nil || !fileResult.Written || fileResult.Output != jsonPath {
		t.Fatalf("file JSON = %q, %+v, %v", out, fileResult, err)
	}

	if err := os.WriteFile(rulesPath, []byte("drift\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := runIngressgen(t, "check", manifest, rulesPath); err == nil {
		t.Fatal("check accepted drift")
	}
	if _, err := runIngressgen(t, "render", writeIngressManifest(t, "INPUT")); err == nil {
		t.Fatal("render accepted INPUT chain")
	}
}

func TestIngressgenApplyCommandUsesSafePath(t *testing.T) {
	manifest := writeIngressManifest(t, "DOCKER-USER")
	dir := t.TempDir()
	logPath := filepath.Join(dir, "calls")
	fake := filepath.Join(dir, "iptables-restore")
	script := "#!/bin/sh\nprintf '%s\\n' \"$*\" >> \"$CALL_LOG\"\ncat >/dev/null\n"
	if err := os.WriteFile(fake, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("CALL_LOG", logPath)
	out, err := runIngressgen(t, "apply", manifest, "--iptables-restore", fake, "--json")
	if err != nil {
		t.Fatal(err)
	}
	var payload map[string]string
	if err := json.Unmarshal([]byte(out), &payload); err != nil || payload["status"] != "ok" {
		t.Fatalf("apply JSON = %q, %v", out, err)
	}
	calls, err := os.ReadFile(logPath)
	if err != nil || string(calls) != "--test --noflush\n--noflush\n" {
		t.Fatalf("apply calls = %q, %v", calls, err)
	}
}
