// Generated by `vybava config init` — do not edit. `vybava config check` fails
// on drift; `vybava config init --force` rewrites it after a vybava upgrade.

/** Key style of a locale catalog. */
export type CatalogStyle =
  /** The key IS the English source text: t('Save'). An `en` file, if present, maps key → key. */
  | 'english-as-key'
  /** Nested JSON addressed by dotted path: meta.title. */
  | 'path';

export interface ScanConfig {
  /** Directories scanned for translation calls, relative to the repo root. */
  roots: string[];
  /** Function name whose first literal argument is a key (default: t). */
  call?: string;
  /** File extensions to scan (default: .ts .tsx .js .jsx). */
  extensions?: string[];
}

export interface CatalogConfig {
  style: CatalogStyle;
  /** File pattern with a `{locale}` placeholder, relative to the repo root. */
  files: string;
  /** Every locale the catalog ships. */
  locales: string[];
  /** Locales every key must carry (default: all). Others are tracked by `lok missing`. */
  required?: string[];
  /** Plural suffixes that make a key a variant of its base (default: _zero _one _two _few _many _other). */
  plurals?: string[];
  /** Shell command run after any write, from the repo root (e.g. a type generator). */
  afterWrite?: string;
  /** Regexes for keys excused from the english-as-key invariant (structured keys like `_help$` whose en value is prose). */
  exempt?: string[];
  /** Source scan for english-as-key catalogs. */
  scan?: ScanConfig;
}

export interface LokConfig {
  catalogs: Record<string, CatalogConfig>;
}

export interface VybavaConfig {
  lok?: LokConfig;
}

/** Identity with types — the config file's default export. */
export const defineConfig = <T extends VybavaConfig>(config: T): T => config;

/** A flat catalog whose keys are the English source text. */
export const englishAsKey = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'english-as-key', files, locales, ...rest });

/** A nested catalog addressed by dotted path. */
export const pathKeys = (
  files: string,
  locales: string[],
  rest: Omit<CatalogConfig, 'style' | 'files' | 'locales'> = {},
): CatalogConfig => ({ style: 'path', files, locales, ...rest });
