package vconfig

import (
	"bytes"
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// helperTS is the generated TypeScript module vybava.config.ts imports. It
// is written by `vybava config init` and re-checked by `vybava config check`
// so a repo never drifts from the shape the binary understands.
//
//go:embed config-helpers.ts
var helperTS string

// ErrHelperDrift means .vybava/config.ts differs from what this binary ships.
var ErrHelperDrift = errors.New(".vybava/config.ts differs from the helpers this vybava ships — run `vybava config init --force`")

// HelperPath is where the helper module lives for a repo root.
func HelperPath(root string) string { return filepath.Join(root, HelperDir, HelperFile) }

// WriteHelpers writes (or with force, overwrites) the helper module.
func WriteHelpers(root string, force bool) (written bool, err error) {
	p := HelperPath(root)
	if existing, err := os.ReadFile(p); err == nil && !force {
		if bytes.Equal(existing, []byte(helperTS)) {
			return false, nil
		}
		return false, ErrHelperDrift
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(p, []byte(helperTS), 0o644)
}

// CheckHelpers reports drift without writing.
func CheckHelpers(root string) error {
	existing, err := os.ReadFile(HelperPath(root))
	if err != nil {
		return fmt.Errorf("%s missing — run `vybava config init`", HelperPath(root))
	}
	if !bytes.Equal(existing, []byte(helperTS)) {
		return ErrHelperDrift
	}
	return nil
}

// StarterConfig is the vybava.config.ts `vybava config init` scaffolds.
const StarterConfig = `import { defineConfig } from './.vybava/config';

// Shared Výbava configuration for this repository — one section per applet.
// Evaluated by bun; the helpers in .vybava/config.ts are generated by
// ` + "`vybava config init`" + ` and drift-checked by ` + "`vybava config check`" + `.
export default defineConfig({});
`
